title: YZU-SOTA's Homepage
page-top-title: YZU-SOTA
top-section-bg-text: Computer Science
home-subtitle: Social Computing and Trustworthy AI Lab&ensp;|&ensp;YZU-SOTA
copyright-text: '&copy; YZU-SOTA 2024-2025. All Rights Reserved.'
